Use versioned filename for NC tarball

diff --git a/bin/ncp-update-nc b/bin/ncp-update-nc
--- a/bin/ncp-update-nc
+++ b/bin/ncp-update-nc
@@ -80,7 +80,7 @@ cleanup() {
   local RET=$?
   set +eE
   echo "Clean up..."
-  rm -rf "$BASEDIR"/nextcloud.tar.bz2 "$BASEDIR"/nextcloud-old
+  rm -rf "$BASEDIR"/nextcloud-${VER}.tar.bz2 "$BASEDIR"/nextcloud-old
   trap "" EXIT
   exit $RET
 }
@@ -90,7 +90,7 @@ trap cleanup EXIT
 ####################
 URL="https://download.nextcloud.com/server/releases/nextcloud-$VER.tar.bz2"
 echo "Download Nextcloud $VER..."
-wget -cq "$URL" -O nextcloud.tar.bz2 || { echo "Error downloading"; exit 1; }
+wget -cq "$URL" -O nextcloud-${VER}.tar.bz2 || { echo "Error downloading"; exit 1; }
 
 # backup
 ####################
@@ -129,8 +129,8 @@ trap rollback_simple INT TERM HUP ERR
 ####################
 echo "Install Nextcloud $VER..."
 mv -T nextcloud nextcloud-old
-tar -xf nextcloud.tar.bz2             # && false # test point
-[ -n "${KEEP_TAR}" ] || rm -rf /var/www/nextcloud.tar.bz2
+tar -xf nextcloud-${VER}.tar.bz2             # && false # test point
+[ -n "${KEEP_TAR}" ] || rm -rf /var/www/nextcloud-${VER}.tar.bz2
 
 # copy old config
 ####################
@@ -163,7 +163,7 @@ rollback() {
   set +eE
   trap "" INT TERM HUP ERR EXIT
   echo -e "Abort\nClean up..."
-  rm -rf /var/www/nextcloud.tar.bz2 "$BASEDIR"/nextcloud-old
+  rm -rf /var/www/nextcloud-${VER}.tar.bz2 "$BASEDIR"/nextcloud-old
   echo "Rolling back to backup $BKP..."
   local TMPDATA
   mkdir -p "$BASEDIR/recovery/"
